CREATE TABLE ANALYZER_GOSALES_HR.A_SALARY1(NAME VARCHAR(20),AGE INT)
     DATA CAPTURE NONE;
     
   CREATE TABLE ANALYZER_GOSALES_HR.A_SALARY2(NAME VARCHAR(20),AGE INT)
     DATA CAPTURE CHANGES; 