-----------------organize by row
CREATE TABLE ANALYZER_GOSALES_HR.A__STUDENT (
  ID INTEGER NOT NULL,
  NAME VARCHAR(25)
) ORGANIZE BY ROW;


-------roganize by column
CREATE TABLE ANALYZER_GOSALES_HR.A_TEACHER (
  ID INTEGER NOT NULL,
  NAME VARCHAR(25)
) ORGANIZE BY ROW;

------organize by dimensions
CREATE TABLE ANALYZER_GOSALES_HR.A_SALES
     (CUSTOMER   VARCHAR(80),
      REGION     CHAR(5),
      YEAR       INTEGER)
   DISTRIBUTE BY HASH (YEAR)
   ORGANIZE BY DIMENSIONS (REGION, YEAR);
   
   
---organize by key sequence   

 CREATE TABLE ANALYZER_GOSALES_HR.A_STUDENT_DATA
     (SCHOOL_ID     INTEGER   NOT NULL,
      PROGRAM_ID    INTEGER   NOT NULL,
      STUDENT_NUM   INTEGER   NOT NULL,
      STUDENT_ID    INTEGER   NOT NULL,
      FIRST_NAME    CHAR(30),
      LAST_NAME     CHAR(30),
      GPA           DOUBLE)
   ORGANIZE BY KEY SEQUENCE
     (STUDENT_ID
       STARTING FROM 1
       ENDING AT 1000000)
     DISALLOW OVERFLOW PCTFREE 10;
     
----ORGANIZE BY INSERT TIME     


 CREATE TABLE ANALYZER_GOSALES_HR.A_TEACHER_DATA
     (SCHOOL_ID     INTEGER   NOT NULL,
      PROGRAM_ID    INTEGER   NOT NULL,
      TEACHER_NUM   INTEGER   NOT NULL,
      TEACHER_ID    INTEGER   NOT NULL,
      FIRST_NAME    CHAR(30),
      LAST_NAME     CHAR(30))
   ORGANIZE BY ROW USING INSERT TIME;
   
   
   
     